# Generated by Django 2.0.5 on 2018-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
                ('bookOrder', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('verseText', models.TextField(verbose_name='text')),
            ],
            options={
                'db_table': 'verses',
                'ordering': ['bookOrder', 'chapter', 'verse'],
            },
        ),
    ]
