"""
Django settings for bibThings project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x3^@uokad67cxo+nh%rt5xn*)gy85vm*+bmo9co7nc1g3fkb%g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bibBot.apps.BibbotConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bibThings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bibThings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

###### Global variables

VERSION="KSV"

"""
FIRST_LINES = {36: 'Genesis', 4812: 'Exodus', 8867: 'Leviticus', 11749: 'Numbers', 15718: 'Deuteronomy',
           18909: 'Joshua', 21070: 'Judges', 23340: 'Ruth', 23651: 'I Samuel', 26641: 'II Samuel',
           29094: 'I Kings', 31990: 'II Kings', 34706: 'I Chronicles', 37378: 'II Chronicles',
           40502: 'Ezra', 41418: 'Nehemiah', 42710: 'Esther', 43352: 'Job', 45937: 'Psalms', 53537: 'Proverbs',
           56015: 'Ecclesiastes', 56711: 'The Song of Solomon', 57076: 'Isaih', 61550: 'Jeremiah',
           66480: 'Lamentations', 66961: 'Ezekiel', 71548: 'Daniel' }
"""

"""
BOOKS = ['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings',
'1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalm','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians',
'1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation']
"""

#BOOK_ABBR_LIST = ['Ge','Ex','Lev','Nu','Dt','Jos','Jdg','Ru','1Sa','2Sa','1Ki','2Ki','1Ch','2Ch','Ezr','Ne','Est',
# 'Job','Ps','Pr','Ecc','SS','Isa','Jer','La','Eze','Da','Hos','Joel','Am','Ob','Jnh','Mic','Na','Hab','Zep','Hag','Zec','Mal','Mt','Mk','Lk','Jn','Ac','Ro','1Co','2Co','Gal','Eph','Php','Col',
#              '1Th','2Th','1Ti','2Ti','Tit','Phm','Heb','Jas','1Pe','2Pe','1Jn','2Jn','3Jn','Jude','Rev']


BOOK_ABBR_LIST = ['Jn','Ac']


NUMBERED_BOOK_ABBR_LIST = ['101 Ge','102 Ex','103 Lev','104 Nu','105 Dt','106 Jos','107 Jdg','108 Ru','109 1Sa','110 2Sa','111 1Ki','112 2Ki','113 1Ch','114 2Ch','115 Ezr','116 Ne','117 Est','118 Job','119 Ps','120 Pr','121 Ecc','122 SS','123 Isa','124 Jer','125 La','126 Eze','127 Da','128 Hos','129 Joel','130 Am','131 Ob','132 Jnh','133 Mic','134 Na','135 Hab','136 Zep','137 Hag','138 Zec','139 Mal','201 Mt','202 Mk','203 Lk','204 Jn','205 Ac','206 Ro','207 1Co','208 2Co','209 Gal','210 Eph','211 Php','212 Col',
              '213 1Th','214 2Th','215 1Ti','216 2Ti','217 Tit','218 Phm','219 Heb','220 Jas','221 1Pe','222 2Pe','223 1Jn','224 2Jn','225 3Jn','226 Jude','227 Rev']


KR_BN_TO_FN_DICT = {'창': '101 Ge', '출': '102 Ex', '레': '103 Lev', '민': '104 Nu', '신': '105 Dt', '수': '106 Jos',
'삿': '107 Jdg', '룻': '108 Ru', '삼상': '109 1Sa', '삼하': '110 2Sa', '왕상': '111 1Ki', '왕하': '112 2Ki',
'대상': '113 1Ch', '대하': '114 2Ch', '스': '115 Ezr', '느': '116 Ne', '에': '117 Est', '욥': '118 Job',
'시': '119 Ps', '잠': '120 Pr', '전': '121 Ecc', '아': '122 SS', '사': '123 Isa', '렘': '124 Jer',
'애': '125 La', '겔': '126 Eze', '단': '127 Da', '호': '128 Hos', '욜': '129 Joel', '암': '130 Am',
'옵': '131 Ob', '욘': '132 Jnh', '미': '133 Mic', '나': '134 Na', '합': '135 Hab', '습': '136 Zep',
'학': '137 Hag', '슥': '138 Zec', '말': '139 Mal', '마': '201 Mt', '막': '202 Mk', '눅': '203 Lk',
'요': '204 Jn', '행': '205 Ac', '롬': '206 Ro', '고전': '207 1Co', '고후': '208 2Co', '갈': '209 Gal',
'엡': '210 Eph', '빌': '211 Php', '골': '212 Col', '살전': '213 1Th', '살후': '214 2Th',
'딤전': '215 1Ti', '딤후': '216 2Ti', '딛': '217 Tit', '몬': '218 Phm', '히': '219 Heb',
'약': '220 Jas', '벧전': '221 1Pe', '벧후': '222 2Pe', '요일': '223 1Jn', '요이': '224 2Jn',
'요삼': '225 3Jn', '유': '226 Jude', '계': '227 Rev'}

KR_BN_TO_EN_BN_DICT = {'창': 'Ge', '출': 'Ex', '레': 'Lev', '민': 'Nu', '신': 'Dt', '수': 'Jos',
'삿': 'Jdg', '룻': 'Ru', '삼상': '1Sa', '삼하': '2Sa', '왕상': '1Ki', '왕하': '2Ki',
'대상': '1Ch', '대하': '2Ch', '스': 'Ezr', '느': 'Ne', '에': 'Est', '욥': 'Job',
'시': 'Ps', '잠': 'Pr', '전': 'Ecc', '아': 'SS', '사': 'Isa', '렘': 'Jer',
'애': 'La', '겔': 'Eze', '단': 'Da', '호': 'Hos', '욜': 'Joel', '암': 'Am',
'옵': 'Ob', '욘': 'Jnh', '미': 'Mic', '나': 'Na', '합': 'Hab', '습': 'Zep',
'학': 'Hag', '슥': 'Zec', '말': 'Mal', '마': 'Mt', '막': 'Mk', '눅': 'Lk',
'요': 'Jn', '행': 'Ac', '롬': 'Ro', '고전': '1Co', '고후': '2Co', '갈': 'Gal',
'엡': 'Eph', '빌': 'Php', '골': 'Col', '살전': '1Th', '살후': '2Th',
'딤전': '1Ti', '딤후': '2Ti', '딛': 'Tit', '몬': 'Phm', '히': 'Heb',
'약': 'Jas', '벧전': '1Pe', '벧후': '2Pe', '요일': '1Jn', '요이': '2Jn',
'요삼': '3Jn', '유': 'Jude', '계': 'Rev'}

"""

DICT1 = {'101 Ge': 'Ge', '102 Ex': 'Ex', '103 Lev': 'Lev', '104 Nu': 'Nu', '105 Dt': 'Dt', '106 Jos': 'Jos','107 Jdg': 'Jdg', '108 Ru': 'Ru', '109 1Sa': '1Sa', '110 2Sa': '2Sa', '111 1Ki': '1Ki', '112 2Ki': '2Ki', '113 1Ch': '1Ch', '114 2Ch': '2Ch', '115 Ezr': 'Ezr', '116 Ne': 'Ne', '117 Est': 'Est', '118 Job': 'Job', '119 Ps': 'Ps', '120 Pr': 'Pr', '121 Ecc': 'Ecc', '122 SS': 'SS', '123 Isa': 'Isa', '124 Jer': 'Jer', '125 La': 'La', '126 Eze': 'Eze', '127 Da': 'Da', '128 Hos': 'Hos', '129 Joel': 'Joel', '130 Am': 'Am', '131 Ob': 'Ob', '132 Jnh': 'Jnh', '133 Mic': 'Mic', '134 Na': 'Na', '135 Hab': 'Hab', '136 Zep': 'Zep', '137 Hag': 'Hag', '138 Zec': 'Zec', '139 Mal': 'Mal', '201 Mt': 'Mt', '202 Mk': 'Mk', '203 Lk': 'Lk', '204 Jn': 'Jn', '205 Ac': 'Ac', '206 Ro': 'Ro', '207 1Co': '1Co', '208 2Co': '2Co', '209 Gal': 'Gal', '210 Eph': 'Eph', '211 Php': 'Php', '212 Col': 'Col', '213 1Th': '1Th', '214 2Th': '2Th', '215 1Ti': '1Ti', '216 2Ti': '2Ti', '217 Tit': 'Tit', '218 Phm': 'Phm', '219 Heb': 'Heb', '220 Jas': 'Jas', '221 1Pe': '1Pe', '222 2Pe': '2Pe', '223 1Jn': '1Jn', '224 2Jn': '2Jn', '225 3Jn': '3Jn', '226 Jude': 'Jude', '227 Rev': 'Rev'}


DICT2 ={'Ge': '101 Ge', 'Ex': '102 Ex', 'Lev': '103 Lev', 'Nu': '104 Nu', 'Dt': '105 Dt', 'Jos': '106 Jos', 'Jdg': '107 Jdg', 'Ru': '108 Ru', '1Sa': '109 1Sa', '2Sa': '110 2Sa', '1Ki': '111 1Ki', '2Ki': '112 2Ki', '1Ch': '113 1Ch', '2Ch': '114 2Ch', 'Ezr': '115 Ezr', 'Ne': '116 Ne', 'Est': '117 Est', 'Job': '118 Job', 'Ps': '119 Ps', 'Pr': '120 Pr', 'Ecc': '121 Ecc', 'SS': '122 SS', 'Isa': '123 Isa', 'Jer': '124 Jer', 'La': '125 La', 'Eze': '126 Eze', 'Da': '127 Da', 'Hos': '128 Hos', 'Joel': '129 Joel', 'Am': '130 Am', 'Ob': '131 Ob', 'Jnh': '132 Jnh', 'Mic': '133 Mic', 'Na': '134 Na', 'Hab': '135 Hab', 'Zep': '136 Zep', 'Hag': '137 Hag', 'Zec': '138 Zec', 'Mal': '139 Mal', 'Mt': '201 Mt', 'Mk': '202 Mk', 'Lk': '203 Lk', 'Jn': '204 Jn', 'Ac': '205 Ac', 'Ro': '206 Ro', '1Co': '207 1Co', '2Co': '208 2Co', 'Gal': '209 Gal', 'Eph': '210 Eph', 'Php': '211 Php', 'Col': '212 Col', '1Th': '213 1Th', '2Th': '214 2Th', '1Ti': '215 1Ti', '2Ti': '216 2Ti', 'Tit': '217 Tit', 'Phm': '218 Phm', 'Heb': '219 Heb', 'Jas': '220 Jas', '1Pe': '221 1Pe', '2Pe': '222 2Pe', '1Jn': '223 1Jn', '2Jn': '224 2Jn', '3Jn': '225 3Jn', 'Jude': '226 Jude', 'Rev': '227 Rev'}
"""

KR_BN_LIST = ['창', '출', '레', '민', '신', '수',
'삿', '룻' '삼상', '삼하', '왕상', '왕하', '대상', '대하', '스', '느', '에', '욥',
'시', '잠', '전', '아', '사', '렘', '애', '겔', '단', '호', '욜', '암',
'옵', '욘', '미', '나', '합', '습', '학', '슥', '말', '마', '막', '눅',
'요', '행', '롬', '고전', '고후', '갈', '엡', '빌', '골', '살전', '살후',
'딤전', '딤후', '딛', '몬', '히', '약', '벧전', '벧후', '요일', '요이', '요삼', '유', '계']

KRBN_ABBR2FULL_DICT = {'창': '창세기', '출': '출애굽기', '레': '레위기', '민': '민수기', '신': '신명기', '수': '여호수아',
'삿': '사사기', '룻': '룻기', '삼상': '사무엘상', '삼하': '사무엘하', '왕상': '열왕기상', '왕하': '열왕기하',
'대상': '역대상', '대하': '역대하', '스': '에스라', '느': '느헤미야', '에': '에스더', '욥': '욥기',
'시': '시편', '잠': '잠언', '전': '전도서', '아': '아가', '사': '이사야', '렘': '예레미야',
'애': '예레미야애가', '겔': '에스겔', '단': '다니엘', '호': '호세아', '욜': '요엘', '암': '아모스',
'옵': '오바댜', '욘': '요나', '미': '미가', '나': '나훔', '합': '하박국', '습': '스바냐',
'학': '학개', '슥': '스가랴', '말': '말라기', '마': '마태복음', '막': '마가복음', '눅': '누가복음',
'요': '요한복음', '행': '사도행전', '롬': '로마서', '고전': '고린도전서', '고후': '고린도후서', '갈': '갈라디아서',
'엡': '에베소서', '빌': '빌립보서', '골': '골로새서', '살전': '데살로니가전서', '살후': '데살로니가후서',
'딤전': '디모데전서', '딤후': '디모데후서', '딛': '디도서', '몬': '빌레몬서', '히': '히브리서',
'약': '야고보서', '벧전': '베드로전서', '벧후': '베드로후서', '요일': '요한1서', '요이': '요한2서',
'요삼': '요한3서', '유': '유다서', '계': '요한계시록'}


"""
BN_ALIASES_UC = [
['Ge', '창', '창세기', '창세', 'Genesis'],
['Ex', '출', '출애굽기',	'출애굽', '탈출기', 'Exodus'],
['Lev', '레', '레위기', '레위', 'Leviticus'],
['Nu', '민', '민수기', '민수', 'Numbers'],
['Dt', '신', '신명기', '신명', 'Deuteronomy'],
['Jos', '수', '여호수아', '여호', 'Joshua'],
['Jdg', '삿', '사사기', '판관', 'Judges'],
['Ru', '룻', '룻기', 'Ruth'],
['1Sa', '삼상', '사무엘상', '1사무', '1 Samuel'],
['2Sa', '삼하', '사무엘하', '2사무', '2 Samuel'],
['1Ki', '왕상', '열왕기상', '1열왕', '1 Kings'],
['2Ki', '왕하', '열왕기하', '2열왕', '2 Kings'],
['1Ch', '대상', '역대상', '1역대', '1 Chronicals'],
['2Ch', '대하', '역대하', '2역대', '2 Chronicals'],
['Ezr', '스', '에스라', '에즈', 'Ezra'],
['Ne', '느', '느헤미야', '느헤', 'Nehemiah'],
['Est', '에', '에스더', '에스', 'Esther'],
['Job', '욥', '욥기'],
['Ps', '시', '시편', 'Psalm', 'Psm'],
['Pr', '잠', '잠언', 'Proverbs', 'Proverb'],
['Ecc', '전', '전도서', '전도', 'Ecclesiastes'],
['SS', '아', '아가', 'Song of Solomon'],
['Isa', '사', '이사야', '이사', 'Isaiah', 'Is'],
['Jer', '렘', '예레미야', '예레', 'Jeremiah'],
['La', '애', '예레미야애가', '애가', 'Lamentations', 'Lamentation'],
['Eze','겔', '에스겔', '에제', 'Ezekiel'],
['Da', '단', '다니엘', '다니', 'Daniel'],
['Hos', '호', '호세아', '호세', 'Hosea'],
['Joel', '욜', '요엘', 'Jo'],
['Am', '암', '아모스', '아모', 'Amos'],
['Ob', '옵', '오바댜', '오바', 'Obadiah'],
['Jnh', '욘', '요나', 'Jonah'],
['Mic', '미', '미가', 'Micah'],
['Na', '나', '나훔', 'Nahum'],
['Hab', '합', '하박국', '하바', 'Habakkuk'],
['Zep', '습', '스바냐', '스바', 'Zephaniah'],
['Hag', '학', '학개', '하깨', 'Haggai'],
['Zec', '슥', '스가랴', '즈가', 'Zechariah'],
['Mal', '말', '말라기', '말라', 'Malachi'],
['Mt', '마', '마태복음', '마태', 'Matthew'],
['Mk', '막', '마가복음', '마르', 'Mark'],
['Lk', '눅', '누가복음', '루가', 'Luke'],
['Jn', '요', '요한복음', '요한', 'John', 'Johan'],
['Ac', '행', '사도행전', '사도', 'Acts', 'Act'],
['Ro', '롬', '로마서', '로마', 'Romans'],
['1Co', '고전', '고린도전서', '1고린', '1 Corinthians'],
['2Co', '고후', '고린도후서', '2고린', '2 Corinthians'],
['Gal', '갈', '갈라디아서', '갈라', 'Galathians'],
['Eph', '엡', '에베소서', '에페', 'Ephesians'],
['Php', '빌', '빌립보서', '필립', 'Philippians'],
['Col', '골', '골로새서', '골로', 'Colossians'],
['1Th', '살전', '데살로니가전서', '1데살', '1 Thessalonians'],
['2Th', '살후', '데살로니가후서', '2데살', '2 Thessalonians'],
['1Ti', '딤전', '디모데전서', '1디모', '1 Timothy'],
['2Ti', '딤후', '디모데후서', '2디모', '2 Timothy'],
['Tit', '딛', '디도서', '디도', 'Titus'],
['Phm', '몬', '빌레몬서', '필레', 'Philemon'],
['Heb', '히', '히브리서', '히브', 'Hebrews'],
['Jas', '약', '야고보서', '야고', 'James'],
['1Pe', '벧전', '베드로전서', '1베드', '1 Peter'],
['2Pe', '벧후', '베드로후서', '2베드', '2 Peter'],
['1Jn', '요일', '요한1서', '요1', '1요', '1요한', '1 John'],
['2Jn', '요이', '요한2서', '요2', '2요', '2요한', '2 John'],
['3Jn', '요삼', '요한3서', '요3', '3요', '3요한', '3 John'],
['Jude', '유', '유다서', '유다', 'Jude'],
['Rev', '계', '요한계시록', '묵시', 'Revelation']
]
"""

BN_ALIASES = [
['ge', '창', '창세기', '창세', 'genesis', 'gen'],
['ex', '출', '출애굽기','출애굽','출애','출에' '탈출기', 'exodus','exod'],
['lev', '레', '레위기', '레위', 'leviticus', 'levi'],
['nu', '민', '민수기', '민수', 'numbers','number','numb','num'],
['dt', '신', '신명기', '신명', 'deuteronomy','deut','deu'],
['jos', '수', '여호수아', '여호수','여호', '여', 'joshua'],
['jdg', '삿', '사사기', '사사','판관', 'judges'],
['ru', '룻', '룻기', '롯','ruth'],
['1sa', '삼상', '사무엘상', '상사무엘,''1사무엘', '1사무', '1 samuel'],
['2sa', '삼하', '사무엘하', '하사무엘','2사무엘', '2사무','2 samuel'],
['1ki', '왕상', '열왕기상', '열왕상','상열왕', '1열왕', '열왕1', '1 kings'],
['2ki', '왕하', '열왕기하', '열왕하','하열왕', '2열왕', '열왕2', '2 kings'],
['1ch', '대상', '역대상', '역상', '1역대', '1 chronicals'],
['2ch', '대하', '역대하', '역하', '2역대', '2 chronicals'],
['ezr', '스', '에스라', '에스', '에즈', 'ezra'],
['ne', '느', '느헤미야', '느헤미아','느헤미', '느헤', 'nehemiah'],
['est', '에', '에스더', '에스', 'esther'],
['job', '욥', '욥기'],
['ps', '시', '시편', 'psalm', 'psm'],
['pr', '잠', '잠언', 'proverbs', 'proverb'],
['ecc', '전', '전도서', '전도', 'ecclesiastes'],
['ss', '아', '아가', 'song of solomon'],
['isa', '사', '이사야', '이사', 'isaiah', 'Is'],
['jer', '렘', '예레미야', '에레미아','예레미', '에레미' '예레','에레' 'jeremiah'],
['la', '애', '예레미야애가','에레미야애가', '애가', 'lamentations', 'lamentation'],
['eze','겔', '에스겔', '에스', '에제', 'ezekiel'],
['da', '단', '다니엘', '다니', 'daniel'],
['hos', '호', '호세아','호새아', '호세', '호새', 'hosea'],
['joel', '욜', '요엘', 'jo'],
['am', '암', '아모스', '아모', 'amos'],
['ob', '옵', '오바댜', '오바', 'obadiah'],
['jnh', '욘', '요나', 'jonah'],
['mic', '미', '미가', 'micah'],
['na', '나', '나훔', 'nahum'],
['hab', '합', '하박국', '하박', 'habakkuk'],
['zep', '습', '스바냐', '스바', 'zephaniah'],
['hag', '학', '학개', '하깨', 'haggai'],
['zec', '슥', '스가랴', '스가', '즈가랴','즈가', 'zechariah'],
['mal', '말', '말라기', '말라', 'malachi'],
['mt', '마', '마태복음', '마태복','마태', 'matthew'],
['mk', '막', '마가복음', '마가복','마가', 'mark'],
['lk', '눅', '누가복음', '누가복','누가', '루가','luke'],
['jn', '요', '요한복음', '요한복','요한', '존', 'john', 'johan'],
['ac', '행', '사도행전', '사도행','사도','사행', 'acts', 'act'],
['ro', '롬', '로마서', '로마', 'romans'],
['1co', '고전', '고린도전서', '고린전','1고린', '고린도1', '고린도전','1 corinthians'],
['2co', '고후', '고린도후서', '고린후','2고린', '고린도2', '고린도후','2 corinthians'],
['gal', '갈', '갈라디아서', '갈라디아', '갈라디','갈라', 'galathians'],
['eph', '엡', '에베소서', '에베소', '에베','에페', 'ephesians'],
['php', '빌', '빌립보서', '빌립보', '빌립','필립', 'philippians'],
['col', '골', '골로새서', '골로새','골로', 'colossians'],
['1th', '살전', '데살로니가전서','데살로니카전서', '데살전', '1데살로니가', '1데살로니카','1데살', '1 thessalonians'],
['2th', '살후', '데살로니가후서','데살로니카후서', '데살후', '2데살로니가', '2데살로니카','2데살', '2 thessalonians'],
['1ti', '딤전', '디모데전서', '디모데전', '디전', '1디모데', '1 timothy'],
['2ti', '딤후', '디모데후서', '디모데후', '디후', '2디모데', '2 timothy'],
['tit', '딛', '디도서', '디도', 'titus'],
['phm', '몬', '빌레몬서', '빌레몬','필레', 'philemon'],
['heb', '히', '히브리서', '히브리','히브', 'hebrews'],
['jas', '약', '야고보서', '야고보','야고', '야','james'],
['1pe', '벧전', '베드로전서', '베드로전','베전', '1베드로', '1 peter', '1peter'],
['2pe', '벧후', '베드로후서', '베드로후','베후', '2베드로', '2 peter', '2peter'],
['1jn', '요일', '요한일서', '요한1서', '요1', '1요', '1요한', '1 john'],
['2jn', '요이', '요한이서', '요한2서', '요2', '2요', '2요한', '2 john'],
['3jn', '요삼', '요한삼서', '요한3서', '요3', '3요', '3요한', '3 john'],
['jude', '유', '유다서', '유다', 'jude'],
['rev', '계', '요한계시록', '계시록', '계시', '요한계', '요계', '묵시', 'revelation']
]


BOOK_STAT= [
    ['ge', 50, 31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 20, 18, 24, 21, 16, 27, 33, 38, 18, 34, 24, 20, 67, 34,
         35, 46, 22, 35, 43, 54, 33, 20, 31, 29, 43, 36, 30, 23, 23, 57, 38, 34, 34, 28, 34, 31, 22, 33, 26],
        ['ex', 40, 22, 25, 22, 31, 23, 30, 29, 28, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27, 25, 26, 37, 30, 33, 18, 40,
         37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38, 29, 31, 43, 38],
        ['lev', 27, 17, 16, 17, 35, 26, 23, 38, 36, 24, 20, 47, 8, 59, 57, 33, 34, 16, 30, 37, 27, 24, 33, 44, 23, 55,
         46, 34],
        ['nu', 36, 54, 34, 51, 49, 31, 27, 89, 26, 23, 36, 35, 16, 33, 45, 41, 35, 28, 32, 22, 29, 35, 41, 30, 25, 19,
         65, 23, 31, 39, 17, 54, 42, 56, 29, 34, 13],
        ['dt', 34, 46, 37, 29, 49, 33, 25, 26, 20, 29, 22, 32, 31, 19, 29, 23, 22, 20, 22, 21, 20, 23, 29, 26, 22, 19,
         19, 26, 69, 28, 20, 30, 52, 29, 12],
        ['jos', 24, 18, 24, 17, 24, 15, 27, 26, 35, 27, 43, 23, 24, 33, 15, 63, 10, 18, 28, 51, 9, 45, 34, 16, 33],
        ['jdg', 21, 36, 23, 31, 24, 31, 40, 25, 35, 57, 18, 40, 15, 25, 20, 20, 31, 13, 31, 30, 48, 25],
        ['ru', 4, 22, 23, 18, 22],
        ['1sa', 31, 28, 36, 21, 22, 12, 21, 17, 22, 27, 27, 15, 25, 23, 52, 35, 23, 58, 30, 24, 42, 16, 23, 28, 23, 43,
         25, 12, 25, 11, 31, 13],
        ['2sa', 24, 27, 32, 39, 12, 25, 23, 29, 18, 13, 19, 27, 31, 39, 33, 37, 23, 29, 32, 44, 26, 22, 51, 39, 25],
        ['1ki', 22, 53, 46, 28, 20, 32, 38, 51, 66, 28, 29, 43, 33, 34, 31, 34, 34, 24, 46, 21, 43, 29, 54],
        ['2ki', 25, 18, 25, 27, 44, 27, 33, 20, 29, 37, 36, 20, 22, 25, 29, 38, 20, 41, 37, 37, 21, 26, 20, 37, 20, 30],
        ['1ch', 29, 54, 55, 24, 43, 41, 66, 40, 40, 44, 14, 47, 41, 14, 17, 29, 43, 27, 17, 19, 8, 30, 19, 32, 31, 31,
         32, 34, 21, 30],
        ['2ch', 36, 18, 17, 17, 22, 14, 42, 22, 18, 31, 19, 23, 16, 23, 14, 19, 14, 19, 34, 11, 37, 20, 12, 21, 27, 28,
         23, 9, 27, 36, 27, 21, 33, 25, 33, 26, 23],
        ['ezr', 10, 11, 70, 13, 24, 17, 22, 28, 36, 15, 44],
        ['ne', 13, 11, 20, 38, 17, 19, 19, 72, 18, 37, 40, 36, 47, 31],
        ['est', 10, 22, 23, 15, 17, 14, 14, 10, 17, 32, 3],
        ['job', 42, 22, 13, 26, 21, 27, 30, 21, 22, 35, 22, 20, 25, 28, 22, 35, 22, 16, 21, 29, 29, 34, 30, 17, 25, 6,
         14, 21, 28, 25, 31, 40, 22, 33, 37, 16, 33, 24, 41, 30, 32, 26, 17],
        ['ps', 150, 6, 11, 9, 9, 13, 11, 18, 10, 21, 18, 7, 9, 6, 7, 5, 11, 15, 51, 15, 10, 14, 32, 6, 10, 22, 11, 14,
         9, 11, 13, 25, 11, 22, 23, 28, 13, 40, 23, 14, 18, 14, 12, 5, 27, 18, 12, 10, 15, 21, 23, 21, 11, 7, 9, 24, 14,
         12, 12, 18, 14, 9, 13, 12, 11, 14, 20, 8, 36, 37, 6, 24, 20, 28, 23, 11, 13, 21, 72, 13, 20, 17, 8, 19, 13, 14,
         17, 7, 19, 53, 17, 16, 16, 5, 23, 11, 13, 12, 9, 9, 5, 8, 29, 22, 35, 45, 48, 43, 14, 31, 7, 10, 10, 9, 8, 18,
         19, 2, 29, 176, 7, 8, 9, 4, 8, 5, 6, 5, 6, 8, 8, 3, 18, 3, 3, 21, 26, 9, 8, 24, 14, 10, 8, 12, 15, 21, 10, 20,
         14, 9, 6],
        ['pr', 31, 33, 22, 35, 27, 23, 35, 27, 36, 18, 32, 31, 28, 25, 35, 33, 33, 28, 24, 29, 30, 31, 29, 35, 34, 28,
         28, 27, 28, 27, 33, 31],
        ['ecc', 12, 18, 26, 22, 17, 19, 12, 29, 17, 18, 20, 10, 14],
        ['ss', 8, 17, 17, 11, 16, 16, 12, 14, 14],
        ['isa', 66, 31, 22, 26, 6, 30, 13, 25, 23, 20, 34, 16, 6, 22, 32, 9, 14, 14, 7, 25, 6, 17, 25, 18, 23, 12, 21,
         13, 29, 24, 33, 9, 20, 24, 17, 10, 22, 38, 22, 8, 31, 29, 25, 28, 28, 25, 13, 15, 22, 26, 11, 23, 15, 12, 17,
         13, 12, 21, 14, 21, 22, 11, 12, 19, 11, 25, 24],
        ['jer', 52, 19, 37, 25, 31, 31, 30, 34, 23, 25, 25, 23, 17, 27, 22, 21, 21, 27, 23, 15, 18, 14, 30, 40, 10, 38,
         24, 22, 17, 32, 24, 40, 44, 26, 22, 19, 32, 21, 28, 18, 16, 18, 22, 13, 30, 5, 28, 7, 47, 39, 46, 64, 34],
        ['la', 5, 22, 22, 66, 22, 22],
        ['eze', 48, 28, 10, 27, 17, 17, 14, 27, 18, 11, 22, 25, 28, 23, 23, 8, 63, 24, 32, 14, 44, 37, 31, 49, 27, 17,
         21, 36, 26, 21, 26, 18, 32, 33, 31, 15, 38, 28, 23, 29, 49, 26, 20, 27, 31, 25, 24, 23, 35],
        ['da', 12, 21, 49, 100, 34, 30, 29, 28, 27, 27, 21, 45, 13],
        ['hos', 14, 9, 25, 5, 19, 15, 11, 16, 14, 17, 15, 11, 15, 15, 10],
        ['joel', 3, 20, 32, 21],
        ['am', 9, 15, 16, 15, 13, 27, 14, 17, 14, 15],
        ['ob', 1, 21],
        ['jnh', 4, 16, 11, 10, 11],
        ['mic', 7, 16, 13, 12, 14, 14, 16, 20],
        ['na', 3, 14, 14, 19],
        ['hab', 3, 17, 20, 19],
        ['zep', 3, 18, 15, 20],
        ['hag', 2, 15, 23],
        ['zec', 14, 17, 17, 10, 14, 11, 15, 14, 23, 17, 12, 17, 14, 9, 21],
        ['mal', 4, 14, 17, 18, 6],
        ['mt', 28, 25, 23, 17, 25, 48, 34, 29, 34, 38, 42, 30, 50, 58, 36, 39, 28, 27, 35, 30, 34, 46, 46, 39, 51, 46,
         75, 66, 20],
        ['mk', 16, 45, 28, 35, 41, 43, 56, 37, 38, 50, 52, 33, 44, 37, 72, 47, 20],
        ['lk', 24, 80, 52, 38, 44, 39, 49, 50, 56, 62, 42, 54, 59, 35, 35, 32, 31, 37, 43, 48, 47, 38, 71, 56, 53],
        ['jn', 21, 51, 25, 36, 54, 47, 71, 53, 59, 41, 42, 57, 50, 38, 31, 27, 33, 26, 40, 42, 31, 25],
        ['ac', 28, 26, 47, 26, 37, 42, 15, 60, 40, 43, 48, 30, 25, 52, 28, 41, 40, 34, 28, 40, 38, 40, 30, 35, 27, 27,
         32, 44, 31],
        ['ro', 16, 32, 29, 31, 25, 21, 23, 25, 39, 33, 21, 36, 21, 14, 23, 33, 27],
        ['1co', 16, 31, 16, 23, 21, 13, 20, 40, 13, 27, 33, 34, 31, 13, 40, 58, 24],
        ['2co', 13, 24, 17, 18, 18, 21, 18, 16, 24, 15, 18, 33, 21, 13],
        ['gal', 6, 24, 21, 29, 31, 26, 18],
        ['eph', 6, 23, 22, 21, 32, 33, 24],
        ['php', 4, 30, 30, 21, 23],
        ['col', 4, 29, 23, 25, 18],
        ['1th', 5, 10, 20, 13, 18, 28],
        ['2th', 3, 12, 17, 18],
        ['1ti', 6, 20, 15, 16, 16, 25, 21],
        ['2ti', 4, 18, 26, 17, 22],
        ['tit', 3, 16, 15, 15],
        ['phm', 1, 25],
        ['heb', 13, 14, 18, 19, 16, 14, 20, 28, 13, 28, 39, 40, 29, 25],
        ['jas', 5, 27, 26, 18, 17, 20],
        ['1pe', 5, 25, 25, 22, 19, 14],
        ['2pe', 3, 21, 22, 18],
        ['1jn', 5, 10, 29, 24, 21, 21],
        ['2jn', 1, 13],
        ['3jn', 1, 15],
        ['jude', 1, 25],
        ['rev', 22, 20, 29, 22, 11, 14, 17, 17, 13, 21, 11, 19, 17, 18, 20, 8, 21, 18, 24, 21, 15, 27, 21]
    ]

